spring.application.name=Bank Management
spring.datasource.url=jdbc:mysql://localhost:3306/railway
spring.datasource.username=root
spring.datasource.password=Omi@7113

spring.jpa.hibernate.ddl-auto=update