spring.application.name=Bank Management
spring.datasource.url=jdbc:mysql://viaduct.proxy.rlwy.net:44330/railway
spring.datasource.username=root
spring.datasource.password=kqbmsiqkeDOXdIhlVeedeIyCZlStBLLc

spring.jpa.hibernate.ddl-auto=update